FROM mcr.microsoft.com/vscode/devcontainers/python:0-3.8@sha256:e4d2d718c27531232f1a7228b01250628625a889f861f3b7406d92a6ef097fcc

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# RUN mkdir /etc/devcontainer
COPY .devcontainer/devcontainer-setup.sh /sbin/devcontainer-setup.sh
COPY requirements.txt requirements-dev.txt /etc/devcontainer/
RUN \
  chmod 0755 /sbin/devcontainer-setup.sh \
  && /sbin/devcontainer-setup.sh

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash
